{% set name = "squarify" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b8a110c8dc5f1cd1402ca12d79764a081e90bfc445346cfa166df929753ecb46

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=2.6,<=2.7|>=3.5
    - pip
  run:
    - python >=2.6,<=2.7|>=3.5
    - matplotlib-base

test:
  imports:
    - squarify

about:
  home: https://github.com/laserson/squarify
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: 'Pure Python implementation of the squarify treemap layout algorithm.'

  description: 'Pure Python implementation of the squarify treemap layout algorithm.'
  doc_url: https://github.com/laserson/squarify
  dev_url: https://github.com/laserson/squarify

extra:
  recipe-maintainers:
    - aaronmussig
